name: Deploy Hugo Site

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Hugo Extended
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.123.7/hugo_extended_0.123.7_linux-amd64.tar.gz
          tar -xzf hugo_extended_0.123.7_linux-amd64.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version

      - name: Gerar site estático
        run: hugo --minify -b https://www.araujo.eng.uerj.br/

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 152.92.238.58 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no araujo@152.92.238.58 'echo "Conexão bem-sucedida!"'

      - name: Enviar arquivos via scp
        run: scp -r public/* araujo@152.92.238.58:/home/araujo/site/
